services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.x  # or your Node version
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
